import type { Config } from 'tailwindcss';
import rtl from 'tailwindcss-rtl';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'sans-serif',
        ],
        display: ['"Space Grotesk"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Courier New"', 'ui-monospace', 'monospace'],
        arabic: ['"Noto Kufi Arabic"', '"Noto Naskh Arabic"', 'Tahoma', 'sans-serif'],
      },
      colors: {
        slate: {
          700: '#32455c',
          800: '#1c2d42',
          900: '#0e1f33',
          950: '#061423',
        },
        brand: {
          50: '#eef5fc',
          100: '#d6e7f6',
          200: '#b0cfea',
          300: '#7dadd9',
          400: '#4886c1',
          500: '#2a68a5',
          600: '#1c5288',
          700: '#17406b',
          800: '#123153',
          900: '#01203f',
          950: '#01162c',
        },
        accent: {
          50: '#e8fffb',
          100: '#c2fff7',
          200: '#8dfdf0',
          300: '#4ff5e7',
          400: '#36ecdf',
          500: '#16cfc2',
          600: '#06a79e',
          700: '#0a847e',
          800: '#0d6864',
          900: '#105553',
          950: '#023635',
        },
        ink: {
          DEFAULT: '#08192b',
          soft: '#16324d',
          muted: '#4a6076',
        },
        surface: {
          DEFAULT: '#f6f9fc',
          raised: '#ffffff',
          sunken: '#eef3f8',
          border: '#dee7f0',
        },
      },
      boxShadow: {
        soft: 'none',
        pop: 'none',
        tile: 'none',
        modal: 'none',
        sm: 'none',
        DEFAULT: 'none',
        md: 'none',
        lg: 'none',
        xl: 'none',
        '2xl': 'none',
        inner: 'none',
      },
      backdropBlur: {
        none: '0',
        sm: '0',
        DEFAULT: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
      },
      keyframes: {
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'zoom-in-95': {
          '0%': { transform: 'scale(0.96)' },
          '100%': { transform: 'scale(1)' },
        },
        'slide-in-up': {
          '0%': { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-from-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.15s ease-out',
        'zoom-in-95': 'zoom-in-95 0.15s ease-out',
        'slide-in-up': 'slide-in-up 0.2s ease-out',
        'slide-in-from-right': 'slide-in-from-right 0.28s cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  },
  safelist: [
    'from-brand-600',
    'via-brand-700',
    'to-brand-800',
    'from-accent-600',
    'via-accent-700',
    'to-accent-800',
    'from-emerald-600',
    'via-emerald-700',
    'to-emerald-800',
    'from-amber-500',
    'via-amber-600',
    'to-amber-700',
    'from-rose-600',
    'via-rose-700',
    'to-rose-800',
    'from-slate-800',
    'via-slate-900',
    'to-slate-950',
  ],
  plugins: [rtl],
};

export default config;
