import type { Config } from 'tailwindcss';
import rtl from 'tailwindcss-rtl';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'sans-serif',
        ],
        display: ['"Space Grotesk"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Courier New"', 'ui-monospace', 'monospace'],
        arabic: ['"Noto Kufi Arabic"', '"Noto Naskh Arabic"', 'Tahoma', 'sans-serif'],
      },
      colors: {
        slate: {
          700: '#3f3f46',
          800: '#27272a',
          900: '#18181b',
          950: '#09090b',
        },
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        accent: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
          950: '#431407',
        },
        ink: {
          DEFAULT: '#0f1419',
          soft: '#1e293b',
          muted: '#475569',
        },
        surface: {
          DEFAULT: '#fafaf9',
          raised: '#ffffff',
          sunken: '#f1f5f4',
          border: '#e7e5e4',
        },
      },
      boxShadow: {
        soft: 'none',
        pop: 'none',
        tile: 'none',
        modal: 'none',
        sm: 'none',
        DEFAULT: 'none',
        md: 'none',
        lg: 'none',
        xl: 'none',
        '2xl': 'none',
        inner: 'none',
      },
      backdropBlur: {
        none: '0',
        sm: '0',
        DEFAULT: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
      },
      keyframes: {
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'zoom-in-95': {
          '0%': { transform: 'scale(0.96)' },
          '100%': { transform: 'scale(1)' },
        },
        'slide-in-up': {
          '0%': { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-from-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.15s ease-out',
        'zoom-in-95': 'zoom-in-95 0.15s ease-out',
        'slide-in-up': 'slide-in-up 0.2s ease-out',
        'slide-in-from-right': 'slide-in-from-right 0.28s cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  },
  safelist: [
    'from-brand-600',
    'via-brand-700',
    'to-brand-800',
    'from-accent-500',
    'via-accent-600',
    'to-accent-700',
    'from-emerald-600',
    'via-emerald-700',
    'to-emerald-800',
    'from-amber-500',
    'via-amber-600',
    'to-amber-700',
    'from-rose-600',
    'via-rose-700',
    'to-rose-800',
    'from-slate-800',
    'via-slate-900',
    'to-slate-950',
  ],
  plugins: [rtl],
};

export default config;
